apiVersion: apps/v1
kind: Deployment
metadata:
  name: normalspringboot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: normalspringboot-app
  template:
    metadata:
      labels:
        app: normalspringboot-app
    spec:
      containers:
        - name: normalspringboot-app-container
          image: srinumani/normalspringboot-app:latest
          ports:
            - containerPort: 9090
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
---
apiVersion: v1
kind: Service
metadata:
  name: normalspringboot-app-service
spec:
  selector:
    app: normalspringboot-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
  type: LoadBalancer
